// SPDX-FileCopyrightText: 2026 Meowdia Community
// SPDX-License-Identifier: MIT OR Apache-2.0

// This file is @generated by `cargo run -p xtask -- iana generate`.
// Source snapshot: iana/snapshots/sdp-parameters.xml.
// IANA SDP Parameters updated: 2026-03-05.

pub const IANA_SDP_PARAMETERS_URL: &str =
    "https://www.iana.org/assignments/sdp-parameters/sdp-parameters.xml";
pub const IANA_SDP_PARAMETERS_SNAPSHOT: &str = "iana/snapshots/sdp-parameters.xml";
pub const IANA_SDP_PARAMETERS_UPDATED: &str = "2026-03-05";

#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[doc = "Known media types from the SDP `media` registry."]
pub enum KnownMediaType {
    #[doc = "IANA token `application`."]
    #[doc = "Reference: RFC 8866."]
    Application,
    #[doc = "IANA token `audio`."]
    #[doc = "Reference: RFC 8866."]
    Audio,
    #[doc = "IANA token `haptics`."]
    #[doc = "Reference: RFC-ietf-avtcore-rtp-haptics-13."]
    Haptics,
    #[doc = "IANA token `image`."]
    #[doc = "Reference: RFC 6466."]
    Image,
    #[doc = "IANA token `message`."]
    #[doc = "Reference: RFC 8866."]
    Message,
    #[doc = "IANA token `text`."]
    #[doc = "Reference: RFC 8866."]
    Text,
    #[doc = "IANA token `video`."]
    #[doc = "Reference: RFC 8866."]
    Video,
}

impl KnownMediaType {
    pub const ALL: &'static [Self] = &[
        Self::Application,
        Self::Audio,
        Self::Haptics,
        Self::Image,
        Self::Message,
        Self::Text,
        Self::Video,
    ];

    pub fn from_name(name: &str) -> Option<Self> {
        match name {
            "application" => Some(Self::Application),
            "audio" => Some(Self::Audio),
            "haptics" => Some(Self::Haptics),
            "image" => Some(Self::Image),
            "message" => Some(Self::Message),
            "text" => Some(Self::Text),
            "video" => Some(Self::Video),
            _ => None,
        }
    }

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Application => "application",
            Self::Audio => "audio",
            Self::Haptics => "haptics",
            Self::Image => "image",
            Self::Message => "message",
            Self::Text => "text",
            Self::Video => "video",
        }
    }

    pub const fn reference(self) -> &'static str {
        match self {
            Self::Application => "RFC 8866",
            Self::Audio => "RFC 8866",
            Self::Haptics => "RFC-ietf-avtcore-rtp-haptics-13",
            Self::Image => "RFC 6466",
            Self::Message => "RFC 8866",
            Self::Text => "RFC 8866",
            Self::Video => "RFC 8866",
        }
    }
}

impl core::fmt::Display for KnownMediaType {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        formatter.write_str(self.as_str())
    }
}

impl core::str::FromStr for KnownMediaType {
    type Err = ();
    fn from_str(value: &str) -> Result<Self, Self::Err> {
        Self::from_name(value).ok_or(())
    }
}

#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[doc = "Known transport protocols from the SDP `proto` registry."]
pub enum KnownTransportProtocol {
    #[doc = "IANA token `DCCP`."]
    #[doc = "Reference: RFC 5762."]
    Dccp,
    #[doc = "IANA token `DCCP/RTP/AVP`."]
    #[doc = "Reference: RFC 5762."]
    DccpRtpAvp,
    #[doc = "IANA token `DCCP/RTP/AVPF`."]
    #[doc = "Reference: RFC 5762."]
    DccpRtpAvpf,
    #[doc = "IANA token `DCCP/RTP/SAVP`."]
    #[doc = "Reference: RFC 5762."]
    DccpRtpSavp,
    #[doc = "IANA token `DCCP/RTP/SAVPF`."]
    #[doc = "Reference: RFC 5762."]
    DccpRtpSavpf,
    #[doc = "IANA token `DCCP/TLS/RTP/SAVP`."]
    #[doc = "Reference: RFC 5764."]
    DccpTlsRtpSavp,
    #[doc = "IANA token `DCCP/TLS/RTP/SAVPF`."]
    #[doc = "Reference: RFC 5764."]
    DccpTlsRtpSavpf,
    #[doc = "IANA token `FEC/UDP`."]
    #[doc = "Reference: RFC 6364."]
    FecUdp,
    #[doc = "IANA token `FLUTE/UDP`."]
    #[doc = "Reference: RFC-mehta-rmt-flute-sdp-05."]
    FluteUdp,
    #[doc = "IANA token `PSTN`."]
    #[doc = "Reference: RFC 7195."]
    Pstn,
    #[doc = "IANA token `RTP/AVP`."]
    #[doc = "Reference: RFC 8866."]
    RtpAvp,
    #[doc = "IANA token `RTP/AVPF`."]
    #[doc = "Reference: RFC 4585."]
    RtpAvpf,
    #[doc = "IANA token `RTP/SAVP`."]
    #[doc = "Reference: RFC 3711."]
    RtpSavp,
    #[doc = "IANA token `RTP/SAVPF`."]
    #[doc = "Reference: RFC 5124."]
    RtpSavpf,
    #[doc = "IANA token `TCP`."]
    #[doc = "Reference: RFC 4145."]
    Tcp,
    #[doc = "IANA token `TCP/BFCP`."]
    #[doc = "Reference: RFC 8856."]
    TcpBfcp,
    #[doc = "IANA token `TCP/DTLS/BFCP`."]
    #[doc = "Reference: RFC 8856."]
    TcpDtlsBfcp,
    #[doc = "IANA token `TCP/DTLS/RTP/SAVP`."]
    #[doc = "Reference: RFC 7850."]
    TcpDtlsRtpSavp,
    #[doc = "IANA token `TCP/DTLS/RTP/SAVPF`."]
    #[doc = "Reference: RFC 7850."]
    TcpDtlsRtpSavpf,
    #[doc = "IANA token `TCP/DTLS/SCTP`."]
    #[doc = "Reference: RFC 8841."]
    TcpDtlsSctp,
    #[doc = "IANA token `TCP/MRCPv2`."]
    #[doc = "Reference: RFC 6787."]
    TcpMrcpv2,
    #[doc = "IANA token `TCP/MSRP`."]
    #[doc = "Reference: RFC 4975."]
    TcpMsrp,
    #[doc = "IANA token `TCP/RTP/AVP`."]
    #[doc = "Reference: RFC 4571."]
    TcpRtpAvp,
    #[doc = "IANA token `TCP/RTP/AVPF`."]
    #[doc = "Reference: RFC 7850."]
    TcpRtpAvpf,
    #[doc = "IANA token `TCP/RTP/SAVP`."]
    #[doc = "Reference: RFC 7850."]
    TcpRtpSavp,
    #[doc = "IANA token `TCP/RTP/SAVPF`."]
    #[doc = "Reference: RFC 7850."]
    TcpRtpSavpf,
    #[doc = "IANA token `TCP/TLS`."]
    #[doc = "Reference: RFC 8122."]
    TcpTls,
    #[doc = "IANA token `TCP/TLS/BFCP`."]
    #[doc = "Reference: RFC 8856."]
    TcpTlsBfcp,
    #[doc = "IANA token `TCP/TLS/MRCPv2`."]
    #[doc = "Reference: RFC 6787."]
    TcpTlsMrcpv2,
    #[doc = "IANA token `TCP/TLS/MSRP`."]
    #[doc = "Reference: RFC 4975."]
    TcpTlsMsrp,
    #[doc = "IANA token `TCP/TLS/RTP/AVP`."]
    #[doc = "Reference: RFC 7850."]
    TcpTlsRtpAvp,
    #[doc = "IANA token `TCP/TLS/RTP/AVPF`."]
    #[doc = "Reference: RFC 7850."]
    TcpTlsRtpAvpf,
    #[doc = "IANA token `TCP/WS/BFCP`."]
    #[doc = "Reference: RFC 8857."]
    TcpWsBfcp,
    #[doc = "IANA token `TCP/WSS/BFCP`."]
    #[doc = "Reference: RFC 8857."]
    TcpWssBfcp,
    #[doc = "IANA token `UDP/BFCP`."]
    #[doc = "Reference: RFC 8856."]
    UdpBfcp,
    #[doc = "IANA token `UDP/DTLS/SCTP`."]
    #[doc = "Reference: RFC 8841."]
    UdpDtlsSctp,
    #[doc = "IANA token `UDP/FEC`."]
    #[doc = "Reference: RFC 6364."]
    UdpFec,
    #[doc = "IANA token `UDP/MBMS-FEC/RTP/AVP`."]
    #[doc = "Reference: RFC 6064."]
    UdpMbmsFecRtpAvp,
    #[doc = "IANA token `UDP/MBMS-FEC/RTP/SAVP`."]
    #[doc = "Reference: RFC 6064."]
    UdpMbmsFecRtpSavp,
    #[doc = "IANA token `UDP/MBMS-REPAIR`."]
    #[doc = "Reference: RFC 6064."]
    UdpMbmsRepair,
    #[doc = "IANA token `UDP/TLS/BFCP`."]
    #[doc = "Reference: RFC 8856."]
    UdpTlsBfcp,
    #[doc = "IANA token `UDP/TLS/RTP/SAVP`."]
    #[doc = "Reference: RFC 5764."]
    UdpTlsRtpSavp,
    #[doc = "IANA token `UDP/TLS/RTP/SAVPF`."]
    #[doc = "Reference: RFC 5764."]
    UdpTlsRtpSavpf,
    #[doc = "IANA token `UDP/TLS/UDPTL`."]
    #[doc = "Reference: RFC 7345."]
    UdpTlsUdptl,
    #[doc = "IANA token `fax`."]
    #[doc = "Reference: RFC 2848."]
    Fax,
    #[doc = "IANA token `pager`."]
    #[doc = "Reference: RFC 2848."]
    Pager,
    #[doc = "IANA token `rtp`."]
    #[doc = "Reference: Note 1."]
    Rtp,
    #[doc = "IANA token `udp`."]
    #[doc = "Reference: RFC 8866."]
    Udp,
    #[doc = "IANA token `udptl`."]
    #[doc = "Reference: http://www.itu.int/rec/recommendation.asp?type=folders&lang=e&parent=T-REC-T.38."]
    Udptl,
    #[doc = "IANA token `vat`."]
    #[doc = "Reference: Note 1."]
    Vat,
    #[doc = "IANA token `voice`."]
    #[doc = "Reference: RFC 2848."]
    Voice,
}

impl KnownTransportProtocol {
    pub const ALL: &'static [Self] = &[
        Self::Dccp,
        Self::DccpRtpAvp,
        Self::DccpRtpAvpf,
        Self::DccpRtpSavp,
        Self::DccpRtpSavpf,
        Self::DccpTlsRtpSavp,
        Self::DccpTlsRtpSavpf,
        Self::FecUdp,
        Self::FluteUdp,
        Self::Pstn,
        Self::RtpAvp,
        Self::RtpAvpf,
        Self::RtpSavp,
        Self::RtpSavpf,
        Self::Tcp,
        Self::TcpBfcp,
        Self::TcpDtlsBfcp,
        Self::TcpDtlsRtpSavp,
        Self::TcpDtlsRtpSavpf,
        Self::TcpDtlsSctp,
        Self::TcpMrcpv2,
        Self::TcpMsrp,
        Self::TcpRtpAvp,
        Self::TcpRtpAvpf,
        Self::TcpRtpSavp,
        Self::TcpRtpSavpf,
        Self::TcpTls,
        Self::TcpTlsBfcp,
        Self::TcpTlsMrcpv2,
        Self::TcpTlsMsrp,
        Self::TcpTlsRtpAvp,
        Self::TcpTlsRtpAvpf,
        Self::TcpWsBfcp,
        Self::TcpWssBfcp,
        Self::UdpBfcp,
        Self::UdpDtlsSctp,
        Self::UdpFec,
        Self::UdpMbmsFecRtpAvp,
        Self::UdpMbmsFecRtpSavp,
        Self::UdpMbmsRepair,
        Self::UdpTlsBfcp,
        Self::UdpTlsRtpSavp,
        Self::UdpTlsRtpSavpf,
        Self::UdpTlsUdptl,
        Self::Fax,
        Self::Pager,
        Self::Rtp,
        Self::Udp,
        Self::Udptl,
        Self::Vat,
        Self::Voice,
    ];

    pub fn from_name(name: &str) -> Option<Self> {
        match name {
            "DCCP" => Some(Self::Dccp),
            "DCCP/RTP/AVP" => Some(Self::DccpRtpAvp),
            "DCCP/RTP/AVPF" => Some(Self::DccpRtpAvpf),
            "DCCP/RTP/SAVP" => Some(Self::DccpRtpSavp),
            "DCCP/RTP/SAVPF" => Some(Self::DccpRtpSavpf),
            "DCCP/TLS/RTP/SAVP" => Some(Self::DccpTlsRtpSavp),
            "DCCP/TLS/RTP/SAVPF" => Some(Self::DccpTlsRtpSavpf),
            "FEC/UDP" => Some(Self::FecUdp),
            "FLUTE/UDP" => Some(Self::FluteUdp),
            "PSTN" => Some(Self::Pstn),
            "RTP/AVP" => Some(Self::RtpAvp),
            "RTP/AVPF" => Some(Self::RtpAvpf),
            "RTP/SAVP" => Some(Self::RtpSavp),
            "RTP/SAVPF" => Some(Self::RtpSavpf),
            "TCP" => Some(Self::Tcp),
            "TCP/BFCP" => Some(Self::TcpBfcp),
            "TCP/DTLS/BFCP" => Some(Self::TcpDtlsBfcp),
            "TCP/DTLS/RTP/SAVP" => Some(Self::TcpDtlsRtpSavp),
            "TCP/DTLS/RTP/SAVPF" => Some(Self::TcpDtlsRtpSavpf),
            "TCP/DTLS/SCTP" => Some(Self::TcpDtlsSctp),
            "TCP/MRCPv2" => Some(Self::TcpMrcpv2),
            "TCP/MSRP" => Some(Self::TcpMsrp),
            "TCP/RTP/AVP" => Some(Self::TcpRtpAvp),
            "TCP/RTP/AVPF" => Some(Self::TcpRtpAvpf),
            "TCP/RTP/SAVP" => Some(Self::TcpRtpSavp),
            "TCP/RTP/SAVPF" => Some(Self::TcpRtpSavpf),
            "TCP/TLS" => Some(Self::TcpTls),
            "TCP/TLS/BFCP" => Some(Self::TcpTlsBfcp),
            "TCP/TLS/MRCPv2" => Some(Self::TcpTlsMrcpv2),
            "TCP/TLS/MSRP" => Some(Self::TcpTlsMsrp),
            "TCP/TLS/RTP/AVP" => Some(Self::TcpTlsRtpAvp),
            "TCP/TLS/RTP/AVPF" => Some(Self::TcpTlsRtpAvpf),
            "TCP/WS/BFCP" => Some(Self::TcpWsBfcp),
            "TCP/WSS/BFCP" => Some(Self::TcpWssBfcp),
            "UDP/BFCP" => Some(Self::UdpBfcp),
            "UDP/DTLS/SCTP" => Some(Self::UdpDtlsSctp),
            "UDP/FEC" => Some(Self::UdpFec),
            "UDP/MBMS-FEC/RTP/AVP" => Some(Self::UdpMbmsFecRtpAvp),
            "UDP/MBMS-FEC/RTP/SAVP" => Some(Self::UdpMbmsFecRtpSavp),
            "UDP/MBMS-REPAIR" => Some(Self::UdpMbmsRepair),
            "UDP/TLS/BFCP" => Some(Self::UdpTlsBfcp),
            "UDP/TLS/RTP/SAVP" => Some(Self::UdpTlsRtpSavp),
            "UDP/TLS/RTP/SAVPF" => Some(Self::UdpTlsRtpSavpf),
            "UDP/TLS/UDPTL" => Some(Self::UdpTlsUdptl),
            "fax" => Some(Self::Fax),
            "pager" => Some(Self::Pager),
            "rtp" => Some(Self::Rtp),
            "udp" => Some(Self::Udp),
            "udptl" => Some(Self::Udptl),
            "vat" => Some(Self::Vat),
            "voice" => Some(Self::Voice),
            _ => None,
        }
    }

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Dccp => "DCCP",
            Self::DccpRtpAvp => "DCCP/RTP/AVP",
            Self::DccpRtpAvpf => "DCCP/RTP/AVPF",
            Self::DccpRtpSavp => "DCCP/RTP/SAVP",
            Self::DccpRtpSavpf => "DCCP/RTP/SAVPF",
            Self::DccpTlsRtpSavp => "DCCP/TLS/RTP/SAVP",
            Self::DccpTlsRtpSavpf => "DCCP/TLS/RTP/SAVPF",
            Self::FecUdp => "FEC/UDP",
            Self::FluteUdp => "FLUTE/UDP",
            Self::Pstn => "PSTN",
            Self::RtpAvp => "RTP/AVP",
            Self::RtpAvpf => "RTP/AVPF",
            Self::RtpSavp => "RTP/SAVP",
            Self::RtpSavpf => "RTP/SAVPF",
            Self::Tcp => "TCP",
            Self::TcpBfcp => "TCP/BFCP",
            Self::TcpDtlsBfcp => "TCP/DTLS/BFCP",
            Self::TcpDtlsRtpSavp => "TCP/DTLS/RTP/SAVP",
            Self::TcpDtlsRtpSavpf => "TCP/DTLS/RTP/SAVPF",
            Self::TcpDtlsSctp => "TCP/DTLS/SCTP",
            Self::TcpMrcpv2 => "TCP/MRCPv2",
            Self::TcpMsrp => "TCP/MSRP",
            Self::TcpRtpAvp => "TCP/RTP/AVP",
            Self::TcpRtpAvpf => "TCP/RTP/AVPF",
            Self::TcpRtpSavp => "TCP/RTP/SAVP",
            Self::TcpRtpSavpf => "TCP/RTP/SAVPF",
            Self::TcpTls => "TCP/TLS",
            Self::TcpTlsBfcp => "TCP/TLS/BFCP",
            Self::TcpTlsMrcpv2 => "TCP/TLS/MRCPv2",
            Self::TcpTlsMsrp => "TCP/TLS/MSRP",
            Self::TcpTlsRtpAvp => "TCP/TLS/RTP/AVP",
            Self::TcpTlsRtpAvpf => "TCP/TLS/RTP/AVPF",
            Self::TcpWsBfcp => "TCP/WS/BFCP",
            Self::TcpWssBfcp => "TCP/WSS/BFCP",
            Self::UdpBfcp => "UDP/BFCP",
            Self::UdpDtlsSctp => "UDP/DTLS/SCTP",
            Self::UdpFec => "UDP/FEC",
            Self::UdpMbmsFecRtpAvp => "UDP/MBMS-FEC/RTP/AVP",
            Self::UdpMbmsFecRtpSavp => "UDP/MBMS-FEC/RTP/SAVP",
            Self::UdpMbmsRepair => "UDP/MBMS-REPAIR",
            Self::UdpTlsBfcp => "UDP/TLS/BFCP",
            Self::UdpTlsRtpSavp => "UDP/TLS/RTP/SAVP",
            Self::UdpTlsRtpSavpf => "UDP/TLS/RTP/SAVPF",
            Self::UdpTlsUdptl => "UDP/TLS/UDPTL",
            Self::Fax => "fax",
            Self::Pager => "pager",
            Self::Rtp => "rtp",
            Self::Udp => "udp",
            Self::Udptl => "udptl",
            Self::Vat => "vat",
            Self::Voice => "voice",
        }
    }

    pub const fn reference(self) -> &'static str {
        match self {
            Self::Dccp => "RFC 5762",
            Self::DccpRtpAvp => "RFC 5762",
            Self::DccpRtpAvpf => "RFC 5762",
            Self::DccpRtpSavp => "RFC 5762",
            Self::DccpRtpSavpf => "RFC 5762",
            Self::DccpTlsRtpSavp => "RFC 5764",
            Self::DccpTlsRtpSavpf => "RFC 5764",
            Self::FecUdp => "RFC 6364",
            Self::FluteUdp => "RFC-mehta-rmt-flute-sdp-05",
            Self::Pstn => "RFC 7195",
            Self::RtpAvp => "RFC 8866",
            Self::RtpAvpf => "RFC 4585",
            Self::RtpSavp => "RFC 3711",
            Self::RtpSavpf => "RFC 5124",
            Self::Tcp => "RFC 4145",
            Self::TcpBfcp => "RFC 8856",
            Self::TcpDtlsBfcp => "RFC 8856",
            Self::TcpDtlsRtpSavp => "RFC 7850",
            Self::TcpDtlsRtpSavpf => "RFC 7850",
            Self::TcpDtlsSctp => "RFC 8841",
            Self::TcpMrcpv2 => "RFC 6787",
            Self::TcpMsrp => "RFC 4975",
            Self::TcpRtpAvp => "RFC 4571",
            Self::TcpRtpAvpf => "RFC 7850",
            Self::TcpRtpSavp => "RFC 7850",
            Self::TcpRtpSavpf => "RFC 7850",
            Self::TcpTls => "RFC 8122",
            Self::TcpTlsBfcp => "RFC 8856",
            Self::TcpTlsMrcpv2 => "RFC 6787",
            Self::TcpTlsMsrp => "RFC 4975",
            Self::TcpTlsRtpAvp => "RFC 7850",
            Self::TcpTlsRtpAvpf => "RFC 7850",
            Self::TcpWsBfcp => "RFC 8857",
            Self::TcpWssBfcp => "RFC 8857",
            Self::UdpBfcp => "RFC 8856",
            Self::UdpDtlsSctp => "RFC 8841",
            Self::UdpFec => "RFC 6364",
            Self::UdpMbmsFecRtpAvp => "RFC 6064",
            Self::UdpMbmsFecRtpSavp => "RFC 6064",
            Self::UdpMbmsRepair => "RFC 6064",
            Self::UdpTlsBfcp => "RFC 8856",
            Self::UdpTlsRtpSavp => "RFC 5764",
            Self::UdpTlsRtpSavpf => "RFC 5764",
            Self::UdpTlsUdptl => "RFC 7345",
            Self::Fax => "RFC 2848",
            Self::Pager => "RFC 2848",
            Self::Rtp => "Note 1",
            Self::Udp => "RFC 8866",
            Self::Udptl => {
                "http://www.itu.int/rec/recommendation.asp?type=folders&lang=e&parent=T-REC-T.38"
            }
            Self::Vat => "Note 1",
            Self::Voice => "RFC 2848",
        }
    }
}

impl core::fmt::Display for KnownTransportProtocol {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        formatter.write_str(self.as_str())
    }
}

impl core::str::FromStr for KnownTransportProtocol {
    type Err = ();
    fn from_str(value: &str) -> Result<Self, Self::Err> {
        Self::from_name(value).ok_or(())
    }
}

#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[doc = "Known bandwidth modifiers from the SDP `bwtype` registry."]
pub enum KnownBandwidthType {
    #[doc = "IANA token `AS`."]
    #[doc = "Reference: RFC 8866, RFC 8859."]
    AsValue,
    #[doc = "IANA token `CT`."]
    #[doc = "Reference: RFC 8866, RFC 8859."]
    Ct,
    #[doc = "IANA token `RR`."]
    #[doc = "Reference: RFC 3556, RFC 8859."]
    Rr,
    #[doc = "IANA token `RS`."]
    #[doc = "Reference: RFC 3556, RFC 8859."]
    Rs,
    #[doc = "IANA token `TIAS`."]
    #[doc = "Reference: RFC 3890, RFC 8859."]
    Tias,
}

impl KnownBandwidthType {
    pub const ALL: &'static [Self] = &[Self::AsValue, Self::Ct, Self::Rr, Self::Rs, Self::Tias];

    pub fn from_name(name: &str) -> Option<Self> {
        match name {
            "AS" => Some(Self::AsValue),
            "CT" => Some(Self::Ct),
            "RR" => Some(Self::Rr),
            "RS" => Some(Self::Rs),
            "TIAS" => Some(Self::Tias),
            _ => None,
        }
    }

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::AsValue => "AS",
            Self::Ct => "CT",
            Self::Rr => "RR",
            Self::Rs => "RS",
            Self::Tias => "TIAS",
        }
    }

    pub const fn reference(self) -> &'static str {
        match self {
            Self::AsValue => "RFC 8866, RFC 8859",
            Self::Ct => "RFC 8866, RFC 8859",
            Self::Rr => "RFC 3556, RFC 8859",
            Self::Rs => "RFC 3556, RFC 8859",
            Self::Tias => "RFC 3890, RFC 8859",
        }
    }
}

impl core::fmt::Display for KnownBandwidthType {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        formatter.write_str(self.as_str())
    }
}

impl core::str::FromStr for KnownBandwidthType {
    type Err = ();
    fn from_str(value: &str) -> Result<Self, Self::Err> {
        Self::from_name(value).ok_or(())
    }
}

#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[doc = "Known network types from the SDP `nettype` registry."]
pub enum KnownNetworkType {
    #[doc = "IANA token `ATM`."]
    #[doc = "Reference: RFC 3108."]
    Atm,
    #[doc = "IANA token `IN`."]
    #[doc = "Reference: RFC 8866."]
    InValue,
    #[doc = "IANA token `PSTN`."]
    #[doc = "Reference: RFC 7195."]
    Pstn,
    #[doc = "IANA token `TN`."]
    #[doc = "Reference: RFC 2848."]
    Tn,
}

impl KnownNetworkType {
    pub const ALL: &'static [Self] = &[Self::Atm, Self::InValue, Self::Pstn, Self::Tn];

    pub fn from_name(name: &str) -> Option<Self> {
        match name {
            "ATM" => Some(Self::Atm),
            "IN" => Some(Self::InValue),
            "PSTN" => Some(Self::Pstn),
            "TN" => Some(Self::Tn),
            _ => None,
        }
    }

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Atm => "ATM",
            Self::InValue => "IN",
            Self::Pstn => "PSTN",
            Self::Tn => "TN",
        }
    }

    pub const fn reference(self) -> &'static str {
        match self {
            Self::Atm => "RFC 3108",
            Self::InValue => "RFC 8866",
            Self::Pstn => "RFC 7195",
            Self::Tn => "RFC 2848",
        }
    }
}

impl core::fmt::Display for KnownNetworkType {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        formatter.write_str(self.as_str())
    }
}

impl core::str::FromStr for KnownNetworkType {
    type Err = ();
    fn from_str(value: &str) -> Result<Self, Self::Err> {
        Self::from_name(value).ok_or(())
    }
}

#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[doc = "Known address types from the SDP `addrtype` registry."]
pub enum KnownAddressType {
    #[doc = "IANA token `E164`."]
    #[doc = "Reference: RFC 7195, RFC 3108."]
    E164,
    #[doc = "IANA token `GWID`."]
    #[doc = "Reference: RFC 3108."]
    Gwid,
    #[doc = "IANA token `IP4`."]
    #[doc = "Reference: RFC 8866."]
    Ip4,
    #[doc = "IANA token `IP6`."]
    #[doc = "Reference: RFC 8866."]
    Ip6,
    #[doc = "IANA token `NSAP`."]
    #[doc = "Reference: RFC 3108."]
    Nsap,
}

impl KnownAddressType {
    pub const ALL: &'static [Self] = &[Self::E164, Self::Gwid, Self::Ip4, Self::Ip6, Self::Nsap];

    pub fn from_name(name: &str) -> Option<Self> {
        match name {
            "E164" => Some(Self::E164),
            "GWID" => Some(Self::Gwid),
            "IP4" => Some(Self::Ip4),
            "IP6" => Some(Self::Ip6),
            "NSAP" => Some(Self::Nsap),
            _ => None,
        }
    }

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::E164 => "E164",
            Self::Gwid => "GWID",
            Self::Ip4 => "IP4",
            Self::Ip6 => "IP6",
            Self::Nsap => "NSAP",
        }
    }

    pub const fn reference(self) -> &'static str {
        match self {
            Self::E164 => "RFC 7195, RFC 3108",
            Self::Gwid => "RFC 3108",
            Self::Ip4 => "RFC 8866",
            Self::Ip6 => "RFC 8866",
            Self::Nsap => "RFC 3108",
        }
    }
}

impl core::fmt::Display for KnownAddressType {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        formatter.write_str(self.as_str())
    }
}

impl core::str::FromStr for KnownAddressType {
    type Err = ();
    fn from_str(value: &str) -> Result<Self, Self::Err> {
        Self::from_name(value).ok_or(())
    }
}
