# SPDX-FileCopyrightText: 2026 Meowdia Community
# SPDX-License-Identifier: MIT OR Apache-2.0

name: CI

on:
  pull_request:

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: fsfe/reuse-action@v5

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: wimpysworld/nothing-but-nix@main
        with:
          root-safe-haven: "8192"
          mnt-safe-haven: "4096"

      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            accept-flake-config = true
      - run: nix develop -c just iana-check
        id: iana
        name: Run IANA drift check
        continue-on-error: true
      - run: nix build .#ci_fmt
        id: fmt
        name: Run `cargo fmt`
        continue-on-error: true
      - run: nix log .#ci_fmt
        if: ${{ always() && steps.fmt.outcome == 'failure' }}
        name: Logs (fmt)
      - run: nix build .#ci_clippy
        id: clippy
        name: Run `cargo clippy`
        continue-on-error: true
      - run: nix log .#ci_clippy
        if: ${{ always() && steps.clippy.outcome == 'failure' }}
        name: Logs (clippy)
      - run: nix build .#ci_test
        id: test
        name: Run `cargo test`
        continue-on-error: true
      - run: nix log .#ci_test
        if: ${{ always() && steps.test.outcome == 'failure' }}
        name: Logs (test)
      - run: nix build .#lib
        id: build
        name: Run nix build
        continue-on-error: true
      - run: nix log .#lib
        if: ${{ always() && steps.build.outcome == 'failure' }}
        name: Logs (build)
      - run: exit 1
        if: ${{ always() && (steps.iana.outcome == 'failure' || steps.fmt.outcome == 'failure' || steps.clippy.outcome == 'failure' || steps.test.outcome == 'failure' || steps.build.outcome == 'failure') }}
        name: Exit on failure
